Gradle copy to mods task
jaghaimo/stelnet pull request #27
Opened 2021-04-27 14:24 UTC by mnukka

2021-04-27 15:09 UTC, jaghaimo commented
Please use the default file: `gradle.properties` (gitignored). That way you can access the properties directly, and can remove file reading etc. Do also add a `gradle.properties.dist` with an example of correctly set path.

Additionally, please make the task run after build has finished, but instead of throwing skip the copy if the directory is not set (could do with a warning message).

2021-04-27 15:22 UTC, mnukka commented
> Please use the default file: `gradle.properties` (gitignored). That way you can access the properties directly, and can remove file reading etc. 

Are you sure about this? The reason I did not use "gradle.properties" is because this is the default file used by gradle for various settings. It is generally not used for local settings but shared settings.

2021-04-27 15:31 UTC, mnukka commented
> Please use the default file: `gradle.properties` (gitignored). That way you can access the properties directly, and can remove file reading etc. Do also add a `gradle.properties.dist` with an example of correctly set path.
> 
> Additionally, please make the task run after build has finished, but instead of throwing skip the copy if the directory is not set (could do with a warning message).

Can you elaborate the point of building if you have nothing to copy? You can run `gradle build` if you are just interested in the jar file.

2021-04-27 15:51 UTC, jaghaimo commented
> > Additionally, please make the task run after build has finished, but instead of throwing skip the copy if the directory is not set (could do with a warning message).
> 
> Can you elaborate the point of building if you have nothing to copy? You can run `gradle build` if you are just interested in the jar file.

I thought of redefining build as build + (conditional) copy. Perhaps that's a wrong approach. Keeping throw is fine, just point the user to dist file.

2021-04-27 15:54 UTC, jaghaimo commented
> > Please use the default file: `gradle.properties` (gitignored). That way you can access the properties directly, and can remove file reading etc. 
> 
> Are you sure about this? The reason I did not use "gradle.properties" is because this is the default file used by gradle for various shared settings that developers may want to define. It is generally not used for local settings but shared settings.
> 
> I can do it. The need for any shared settings might not be necessary in this project.
> 

Yes please. If for some reason we do end up needing shared properties then we'll revert this and go with custom (local) variation.

2021-04-27 20:16 UTC, jaghaimo requested changes
Happy with this but would be great if you could make it more generic:
gradle.properties:
```
game.dir = C:\\Something\\Starsector
game.executable = starsector.exe (or starsector.sh for Linux)
```
With another task to start the game (depends on copyMod) and copyMod changed so the mod name is not hardcoded (taken from mod_info.json instead).

2021-04-27 20:16 UTC, jaghaimo commented on gradle.properties.dist
> +game.full_path = C:\\Program Files (x86)\\Fractal Softworks\\Starsector\\mods\\stelnet
Could this be made more generic, e.g. full path to the game folder (sans `\\mods\\stelnet`) with `mods` defined somewhere else, and modname taken from the `mod_info.json` via slurper?

2021-04-27 20:21 UTC, jaghaimo commented on build.gradle
> +        throw new GradleException("Missing game.full_path in gradle.properties. See gradle.properties.dist as an example.")
CI fails due to that. Perhaps just a warning (or error) log with this string and early return?

2021-04-28 12:07 UTC, jaghaimo approved these changes

2021-04-28 12:10 UTC, merged